name: Frontend Test

on:
  push:
    branches:
      - origin/master
  pull_request:
    branches:
      - origin/master

jobs:
  frontend-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install
        run: |
          cd frontend
          npm install

      - name: Build
        run: |
          cd frontend
          npm run build
